services:
  db:
    image: postgres:17
    container_name: dev_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSSWORD}
    volumes:
      - pgdata_truco:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

volumes:
  pgdata_truco:
