spring:
  application:
    name: Truco

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true